container_names and links directive
vulpemventures/nigiri pull request #84
Opened 2020-09-04 15:16 UTC by francismars

added container_names
removed deprecated links directive

2020-09-04 16:20 UTC, francismars commented
updated the documentation to reflect the changes on container_names

2020-09-04 16:22 UTC, tiero commented on resources/docker-compose-regtest.yml
>      depends_on:
Here it should depend on bitcoin too. Add - bitcoin here under the depends_on directive

2020-09-04 16:22 UTC, tiero commented on resources/docker-compose-regtest-liquid.yml
>        - electrs-liquid
same here. Add - liquid under depends_on

2020-09-04 16:23 UTC, tiero commented on resources/docker-compose-regtest-liquid.yml
>        - electrs
same here, add - bitcoin  under depends_on

2020-09-05 14:44 UTC, tiero requested changes
Address the comments

2020-09-07 10:25 UTC, tiero commented
Please @francismars add the "it closes <Github Issue URL>" for each ticket you are asking to merge. Thanks

2020-09-07 11:29 UTC, tiero approved these changes

2020-09-07 11:37 UTC, merged